### ISSUE TITLE
RSS di blog

### ISSUE THREAD

**Issue by faultable** [satyakresna/tanya#1]
Halo kak Kresna,

Terima kasih telah menyediakan [RSS](https://www.satyakresna.io/index.xml) di blog nya, dan saya sudah berlangganan sejak lama :))

Ada sedikit masalah terkait penyajian RSS Feed dari pembaca RSS klien yang [saya gunakan](https://readkitapp.com/) dan mungkin berdampak ke pembaca RSS yang lain juga, yakni URL menggunakan format relatif:

Berikut saya sematkan potongan kode yang didapat dari `index.xml`:

```xml
<rss version="2.0">
<channel>
<title>Halo on Satya Kresna</title>
<link>/</link>
<description>Recent content in Halo on Satya Kresna</description>
<generator>Hugo -- gohugo.io</generator>
<language>en-ID</language>
<atom:link href="/index.xml" rel="self" type="application/rss+xml"/>
<item>
<title>Berkarya Dengan Web</title>
<link>/posts/berkarya-dengan-web/</link>
<pubDate>Sat, 31 Oct 2020 08:48:30 +0800</pubDate>
<guid>/posts/berkarya-dengan-web/</guid>
<description>
Segera dipublikasi setelah acara webinar selesai. ☺️
</description>
</item>
```

Yang mana, hasilnya akan menjadi seperti ini di pembaca RSS yang saya gunakan:

![Screen Shot 2020-10-31 at 3 05 40 PM](https://user-images.githubusercontent.com/6561394/97773442-abff3c80-1b8a-11eb-9fd7-535ad1d1668b.png)

Mungkin bisa dibuat absolut sehingga jika pembaca ingin mengakses halaman asli menjadi tidak terlalu sulit 😎

Terima kasih!

**Comment by satyakresna** [comment]
Halo Kak @faultable, makasih sudah memberitahu masalah RSS ini dan makasih juga sudah berlangganan di blog aku. :)) 

Aku juga berlangganan blognya kak Fariz. 👍 

Btw, masalah RSS sudah aku perbaiki.

<img width="701" alt="Screen Shot 2020-11-01 at 13 36 20" src="https://user-images.githubusercontent.com/11099186/97795939-7bc9a380-1c47-11eb-8d4a-3a22e9c15bd1.png">


Silakan dicek ya. :)

**Comment by faultable** [comment]
Confirmed, terima kasih banyak kak Kresna!

Closing...
