### ISSUE TITLE
cara menjalankan file laravel localhost dilaragon

### ISSUE THREAD

**Issue by farel69** [satyakresna/tanya#2]
bagaimana cara agar saya dapat menjalankan file laravel localhost dilaragon

**Comment by satyakresna** [comment]
Halo @farel69, jika ingin menjalankan proyek Laravel di localhost dengan aplikasi Laragon ada dua cara:

1. Klik tombol "Terminal" lalu arahkan ke direktori proyek Laravel kamu dan jalankan perintah `php artisan serve`. Kemudian, ketik `localhost:8000` di address bar browser kamu.
2. Klik kanan di aplikasi Laragon => pilih `www` => klik proyek Laravel kamu (misalnya nama proyek Laravel kamu adalah `coba-laravel`) biasanya ada embel" `.test` di belakangnya. Klik `coba-laravel.test` dan otomatis Apache akan autoreload. Nanti tinggal ketik `coba-laravel.test` di address bar browser kamu.

Selamat mencoba dan terima kasih sudah bertanya ya. Kalau ada masalah terkait hal di atas silakan komen dan berikan gambar-gambar apa saja yang sudah dilakukan ya. 🙏🏻
