### ISSUE TITLE
saya ingin bertanya kenapa program json saya tidak terbaca oleh python 

### ISSUE THREAD

**Issue by susi126** [satyakresna/tanya#6]

**Comment by susi126** [comment]
PS C:\Users\lenovo\Desktop> & C:/Users/lenovo/AppData/Local/Programs/Python/Python310/python.exe c:/Users/lenovo/Desktop/TUBES/TUGASBESAR.py
Traceback (most recent call last):
  File "c:\Users\lenovo\Desktop\TUBES\TUGASBESAR.py", line 5, in <module>
    json_open = open("TUBES.json")                  # Membuka json       
FileNotFoundError: [Errno 2] No such file or directory: 'TUBES.json'     
PS C:\Users\lenovo\Desktop>

**Comment by satyakresna** [comment]
Halo @susi126, ini hasil error nya menyatakan bahwa tidak ada file bernama "TUBES.json". Ada beberapa kemungkinan kenapa file itu tidak ada:

1. Nama file tidak sesuai (huruf besar dan huruf kecil).
2. Lokasi file tidak dalam direktori saat pemanggilan dengan script python.

Silakan dicek kembali ya. Semoga membantu.

**Comment by susi126** [comment]
untuk penulisannya sudah sama namun kemungkinan error di yang kedua lokasi file tidak dalam direktori sama pemanggilan dengan script python, untuk penyimpanan lokasi harusnya di simpan di mana??
