### ISSUE TITLE
PHP Barcode Generator Qrcode 

### ISSUE THREAD

**Issue by fansyah98** [satyakresna/tanya#7]
An uncaught Exception was encountered
Type: Error

Message: Call to undefined method Endroid\QrCode\QrCode::writeFile()

Filename: C:\xampp\htdocs\gudang\application\views\barang\data_barang.php

Line Number: 58

Backtrace:

File: C:\xampp\htdocs\gudang\application\libraries\Template.php
Line: 18
Function: view

File: C:\xampp\htdocs\gudang\application\controllers\Barang.php
Line: 21
Function: load

File: C:\xampp\htdocs\gudang\index.php
Line: 315
Function: require_once

Plis help mee 
![Screenshot (468)](https://user-images.githubusercontent.com/66173468/157226618-40867623-7bb5-43f8-aa19-142fbb7ea480.png)

**Comment by satyakresna** [comment]
Halo @fansyah98, kalau kamu cek kembali dari error messagenya sudah menyatakan dengan jelas bahwa tidak ada method bernama  `writeFile()` pada class `Endroid\QrCode\QrCode`.

**Comment by fansyah98** [comment]
@satyakresna ada video tutorial nya gak kalo ada bagi saya ka minta .

**Comment by satyakresna** [comment]
Maaf, saya tidak punya video tutorialnya.
